// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAMQVa065q9TFK8_K2-WtHaDyzANWySRw',
    appId: '1:335374423894:android:b27190ae4209b2355968f7',
    messagingSenderId: '335374423894',
    projectId: 'flutter-flavor-sample',
    storageBucket: 'flutter-flavor-sample.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA11zuXSSupQtFI_UxAarZClSIa1m0rIM',
    appId: '1:335374423894:ios:4068d55ea572e64b5968f7',
    messagingSenderId: '335374423894',
    projectId: 'flutter-flavor-sample',
    storageBucket: 'flutter-flavor-sample.appspot.com',
    androidClientId: '335374423894-fq90hgtqlq976cua6f2296mnee96ij7e.apps.googleusercontent.com',
    iosClientId: '335374423894-tijqn5mv90s1are2ek8vu39ik79iso5m.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFlavorSample.prod',
  );
}
